Fe 2 - Digital Cash - Creation objects Referred to the json schema
dedis/popstellar pull request #1040
Opened 2022-05-20 10:06 UTC by zoemarin

Creation of the objects and the tests

2022-05-20 10:28 UTC, Tesa27 requested changes
Good job, the naming convention is not respected in almost all the functions, I think I covered them all so it is a good sanity check is after commiting the changes if y comments are outdated all the function names should be good.

2022-05-20 10:28 UTC, Tesa27 commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/model/objects/Transaction_object.java
> +  public List<PublicKey> get_senders_transaction() {
Camel Case should be used for function names in Java

2022-05-20 10:28 UTC, Tesa27 commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/model/objects/Transaction_object.java
> +  public List<String> get_receivers_hash_transaction() {
Same here

2022-05-20 10:28 UTC, Tesa27 commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/model/objects/Transaction_object.java
> +  public List<PublicKey> get_receivers_transaction(Map<String, PublicKey> map_hash_key) {
Same here

2022-05-20 10:28 UTC, Tesa27 commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/model/objects/Transaction_object.java
> +  public boolean is_receiver(PublicKey publicKey) {
Same here

2022-05-20 10:28 UTC, Tesa27 commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/model/objects/Transaction_object.java
> +  public String compute_sig_outputs_inputs(KeyPair keyPair) throws GeneralSecurityException {
Same here

2022-05-20 10:28 UTC, Tesa27 commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/model/objects/Transaction_object.java
> +  public int get_miniLao_per_receiver(PublicKey receiver) {
Same here

2022-05-20 10:28 UTC, Tesa27 commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/model/objects/Transaction_object.java
> +    // }
I think this should be included it is a good sanity check, but maybe have a more explicit comment

2022-05-20 10:28 UTC, Tesa27 commented on fe2-android/app/src/test/java/com/github/dedis/popstellar/model/objects/Input_objectTest.java
> +public class Input_objectTest {
Also should be Camel Case

2022-05-20 10:28 UTC, Tesa27 commented on fe2-android/app/src/test/java/com/github/dedis/popstellar/model/objects/Input_objectTest.java
> +  public void get_tx_out_indexTest() {
Same here

2022-05-20 10:28 UTC, Tesa27 commented on fe2-android/app/src/test/java/com/github/dedis/popstellar/model/objects/Input_objectTest.java
> +  public void get_tx_out_hashTest() {
Same here

2022-05-20 10:28 UTC, Tesa27 commented on fe2-android/app/src/test/java/com/github/dedis/popstellar/model/objects/Input_objectTest.java
> +  public void get_scriptTest() {
Same here

2022-05-20 10:28 UTC, Tesa27 commented on fe2-android/app/src/test/java/com/github/dedis/popstellar/model/objects/Output_objectTest.java
> +public class Output_objectTest {
Same here

2022-05-20 10:28 UTC, Tesa27 commented on fe2-android/app/src/test/java/com/github/dedis/popstellar/model/objects/Output_objectTest.java
> +  public void get_valueTest() {
Same here

2022-05-20 10:28 UTC, Tesa27 commented on fe2-android/app/src/test/java/com/github/dedis/popstellar/model/objects/Output_objectTest.java
> +  public void get_scriptTest() {
Same here

2022-05-20 10:28 UTC, Tesa27 commented on fe2-android/app/src/test/java/com/github/dedis/popstellar/model/objects/Script_input_objectTest.java
> +  public void getsigtest() {
This is not even snake case, to be changed into Camel Case

2022-05-20 10:28 UTC, Tesa27 commented on fe2-android/app/src/test/java/com/github/dedis/popstellar/model/objects/Script_output_objectTest.java
> +public class Script_output_objectTest {
To be changed to Camel case

2022-05-20 10:28 UTC, Tesa27 commented on fe2-android/app/src/test/java/com/github/dedis/popstellar/model/objects/Script_output_objectTest.java
> +  public void get_typeTest() {
Same here

2022-05-20 10:28 UTC, Tesa27 commented on fe2-android/app/src/test/java/com/github/dedis/popstellar/model/objects/Transaction_objectTest.java
> +public class Transaction_objectTest {
Same here

2022-05-20 12:43 UTC, Tesa27 submitted a review, later dismissed
LGTM

2022-06-01 20:46 UTC, GabrielFleischer approved these changes
LGTM

2022-06-01 20:47 UTC, merged