Meeting tests
dedis/popstellar pull request #1117
Opened 2022-06-14 13:56 UTC by Tesa27

2022-06-17 07:08 UTC, lourkeur submitted a review, later dismissed

2022-06-17 17:12 UTC, tuomas-p requested changes
Minor change request for the inverted test names, otherwise good job!

2022-06-18 12:48 UTC, lourkeur approved these changes

2022-06-18 12:48 UTC, lourkeur commented on be2-scala/src/test/scala/ch/epfl/pop/pubsub/graph/validators/MeetingValidatorSuite.scala
> +    println(dbActorRef)
```suggestion
```

2022-06-18 15:29 UTC, tuomas-p approved these changes
Looks good to me now!

2022-06-18 16:04 UTC, merged