Make sure the karate tests produces good reports
dedis/popstellar pull request #1278
Opened 2022-10-19 11:20 UTC by GabrielFleischer

This PR review the report system to make sure readable and useable reports are produced

2022-10-20 19:19 UTC, Warhedgehog requested changes
Nice work, just the little comment error afaiac

2022-10-21 06:48 UTC, GabrielFleischer commented on tests/karate/src/test/java/be/BackEndTest.java
> +   * It will execute all frontend tests and generate a report
Yes 😅

2022-10-21 06:48 UTC, GabrielFleischer commented on tests/karate/src/test/java/be/BackEndTest.java
> +   * It will execute all frontend tests and generate a report
```suggestion
   * It will execute all backend tests and generate a report
```

2022-10-21 07:36 UTC, Warhedgehog approved these changes
LGTM

2022-10-22 09:12 UTC, merged