Improve Karate CI to push the generated reports on a branch
dedis/popstellar pull request #1283
Opened 2022-10-24 12:43 UTC by GabrielFleischer

2022-10-24 15:56 UTC, jbsv requested changes
I would remove many "always" conditions

2022-10-24 15:56 UTC, jbsv commented on .github/workflows/karate.yml
> +        if: ${{ always() }} # execute even if previous steps failed
I doubt this one is useful

2022-10-24 15:56 UTC, jbsv commented on .github/workflows/karate.yml
> +        if: ${{ always() }} # execute even if previous steps failed
I would remove this one

2022-10-24 15:56 UTC, jbsv commented on .github/workflows/karate.yml
> +        if: ${{ always() }} # execute even if previous steps failed
if the previous git commands fail, this one seems useless too.

2022-10-24 15:56 UTC, jbsv commented on .github/workflows/karate.yml
> +        if: ${{ always() }} # execute even if previous steps failed
same

2022-10-24 15:56 UTC, jbsv commented on .github/workflows/karate.yml
> +        if: ${{ always() }} # execute even if previous steps failed
same

2022-10-24 15:56 UTC, jbsv commented on .github/workflows/karate.yml
> +        if: ${{ always() }} # execute even if previous steps failed
same

2022-10-24 20:11 UTC, pierluca reviewed
I'm a bit worried that the `always()` might backfire if some reporting steps fail.
However, we still need the reporting to run if the tests fail.
Is there something not as strong as `always()` that would still run despite the test failures ?

2022-10-26 14:30 UTC, jbsv approved these changes
LGTM

2022-10-26 14:30 UTC, merged