Work fe2 jpluss drawer
dedis/popstellar pull request #1343
Opened 2023-01-10 14:57 UTC by Warhedgehog

2023-01-17 10:12 UTC, GabrielFleischer requested changes
Very great !

It's good to see things take form.

I found some small issues, happy to approve once they're addressed 😄

2023-01-17 10:12 UTC, GabrielFleischer commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/ui/navigation/LaoViewModel.java
> + */
I think this comment is outdated too

2023-01-17 10:12 UTC, GabrielFleischer commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/ui/navigation/LaoViewModel.java
> +  }
Oh, it went here.

Makes sense

2023-01-17 10:12 UTC, GabrielFleischer commented on fe2-android/app/src/test/ui/robolectric/com/github/dedis/popstellar/ui/socialmedia/ChirpListAdapterTest.java
> +          .putExtra(Constants.LAO_ID_EXTRA, "");
Just for the sake of consistency, could you set the LAO_ID ?
```suggestion
          .putExtra(Constants.LAO_ID_EXTRA, LAO_ID);
```

2023-01-17 16:16 UTC, Warhedgehog commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/ui/navigation/LaoActivity.java
> +  }
Is the injection not done in the constructor in viewmodels ? Because if yes I'd rather leave it here for the sake of simplicity.

2023-01-18 10:50 UTC, GabrielFleischer approved these changes
LGTM

2023-01-18 11:12 UTC, merged