Social - make chirp like/dislike exclusive
dedis/popstellar pull request #1460
Opened 2023-03-16 19:57 UTC by dayan9265

These changes makes that if a user likes a chirp that he previously had disliked, it will remove the dislike reaction (same thing for a liked chirp). This small changes avoid the situation of chirp being liked and disliked which in theory doesn't make a lot of sense.

2023-03-17 12:40 UTC, MeKHell requested changes

2023-03-17 12:42 UTC, MeKHell requested changes
Simple refactoring needed.

2023-03-19 13:34 UTC, Tyratox commented on fe1-web/src/features/social/components/ChirpCard.tsx
> +    const reactionToRemove = isThumbsUp ? '👎' : '👍';
What about

```suggestion
  const thumbsPressed = (reactionToAdd: '👍' | '👎') => {
    const reactionToRemove = isThumbsUp ? '👎' : '👍';
```

2023-03-19 13:34 UTC, Tyratox commented on fe1-web/src/features/social/components/ChirpCard.tsx
> +  const thumbsDownPressed = () => thumbsPressed(false);
If you need to pass an argument to a function feel free to write

`onPress={() => thumbsPressed("👍")}`

in the component directly. If there are no arguments, `onPress={someFunction}` is usually preferred.

2023-03-22 07:48 UTC, MeKHell approved these changes
This looks good to me

2023-03-23 10:32 UTC, Tyratox approved these changes
Looks good to me as well 😊

2023-03-24 15:03 UTC, merged