Redefine sendResult method
dedis/popstellar pull request #1492
Opened 2023-04-05 13:40 UTC by MariemBaccari

This is a small PR that redefines the sendResult method to support sending a map associating a channel to a slice of messages as preparation work for the implementation of the heartbeat and getMessagesById methods. 
In that direction, it fixes previous tests that use sendResult by adding the new argument which will not be used but is necessary since fakeSockets implement Socket.

2023-04-06 14:52 UTC, Nazianzenov reviewed
LGTM overall, just added a comment to confirm the behavior of your new code.

2023-04-11 10:02 UTC, Nazianzenov commented on be1-go/network/socket/socket.go
> +	} else if res != nil {
alright!

2023-04-11 10:03 UTC, Nazianzenov submitted a review, later dismissed
LGTM

2023-04-11 10:50 UTC, Anghul requested changes
Good job, just a remark with the checks in answer, who don't cover all cases and aren't necessarily clean.

2023-04-11 12:05 UTC, MariemBaccari commented on be1-go/message/answer/answer.go
>  }
I see what you mean but here we only have access to a []byte so I don't really see a way to check which field is nil except by trying to Unmarshal it twice in two different data structures.

2023-04-11 13:29 UTC, Anghul commented on be1-go/message/answer/answer.go
>  }
Yeah, you're right, but at least please find a way to not lose error messages.

2023-04-11 14:21 UTC, MariemBaccari commented on be1-go/message/answer/answer.go
>  }
I just pushed a commit [200e886]. It gives every "trial" a separate error variable and combines them before returning. Does this properly address your comment ?

2023-04-11 15:26 UTC, Anghul approved these changes
LGTM

2023-04-11 15:37 UTC, merged