Connection to multiple servers
dedis/popstellar pull request #1493
Opened 2023-04-07 08:49 UTC by matteosz

2023-04-10 18:01 UTC, simone-kalbermatter submitted a review, later dismissed
Impressive work! Clean, well documented and keeps the existing structure.

2023-04-11 19:12 UTC, Warhedgehog requested changes
Impressive work and well documented 👍 A couple question on my end

2023-04-11 19:12 UTC, Warhedgehog commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/repository/remote/MultiConnection.java
I'm missing the point of having the architecture done so. Why treating the first connection different than the others ? By that I mean that I would imagine the result to be simpler with simply populating the connection with every connection including the first one

2023-04-11 19:23 UTC, matteosz commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/ui/lao/LaoActivity.java
> -
Yeah I just realised that I've committed some conflicting and unwanted changes due to a previous merge I've done 😅 , I'll fix that

2023-04-12 20:18 UTC, Warhedgehog commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/repository/remote/MultiConnection.java
Makes sense 👍

2023-04-12 20:18 UTC, Warhedgehog approved these changes
LGTM, great work !

2023-04-12 21:02 UTC, merged