Fix bug duplicates list of attendees when re-opening roll call
dedis/popstellar pull request #1502
Opened 2023-04-12 15:36 UTC by dayan9265

This PR fixes the issue #1478, where there could be duplicate attendees shown on screen. The bug simply comes from the fact that there was no check if there was duplicates when creating the new list of `attendeePopTokens`. There is also two added tests that fails with the previous implementation. (The code to ensure that there is no duplicates is not really "clean", so any idea to make it cleaner would be welcomed :) )

2023-04-13 18:06 UTC, MeKHell requested changes
The code needs to be simplified at one point. Otherwise it seems to be good.

2023-04-13 19:41 UTC, Tyratox reviewed
Hmm honestly while this probably solves the problem I feel like it is not the best solution. In theory https://github.com/dedis/popstellar/blob/master/fe1-web/src/features/rollCall/screens/RollCallScanner.tsx#L114 should already check for duplicates and remove them.. Did you find you why this does not happen? Is some navigation parameter not passed correctly?

It might be because the navigation parameter is still set while `rollCall.attendees` is now filled too resulting in doubling the list?

https://github.com/dedis/popstellar/blob/master/fe1-web/src/features/rollCall/screens/ViewSingleRollCall.tsx#L46-L47

2023-04-13 19:41 UTC, Tyratox commented on fe1-web/src/features/rollCall/components/AttendeeList.tsx
> +              {STRINGS.roll_call_attendees}
Nice catch!

2023-04-14 09:48 UTC, dayan9265 commented
> It might be because the navigation parameter is still set while `rollCall.attendees` is now filled too resulting in doubling the list?

Yes that was the issue, both `attendeePopTokens` and `rollCall?.attendees` contained the same pop tokens

>But I would have assumed that
https://github.com/dedis/popstellar/blob/master/fe1-web/src/features/rollCall/components/RollCallOpen.tsx#L93
already clears it 🤔 Or did you find something else?

I realize that my title is wrong ^^', the duplication happens when we click on `Scan PoPTokens` multiple times (and not when closing the roll call, so this code is not called). 

Maybe the problems come from here?
https://github.com/dedis/popstellar/blob/master/fe1-web/src/features/rollCall/screens/RollCallScanner.tsx#L223
Since it gives all the scanned tokens including the previously scanned token, is it better to modify this part to make it so it only give as a parameter the newly scanned tokens?

2023-04-16 11:38 UTC, Tyratox commented
Oh I see so what happens is
1) you scan some tokens `x` and `y`
2) go back to token list screen, this passes `x` and `y` as navigation parameters 
3) close roll call, stores `x` and `y` in `rollCall.attendees`
4) re-open roll call
5) scan new tokens. here it should not be possible to scan the duplicate tokens since `rollCall.attendees` is passed to the scanner and due to https://github.com/dedis/popstellar/blob/master/fe1-web/src/features/rollCall/screens/RollCallScanner.tsx#L114
6) when going back to the token list screen `rollCall.attendees` and `attendeePopTokensStrings` are the exact same set.

Now if I am not mistaken, we should be fine if we always used `attendeePopTokensStrings` if it is non-empty and `rollCall.attendees` otherwise? This works under the assumption that `attendeePopTokensStrings` are always more up-to-date if they exist and I think that should hold? The only time `attendeePopTokensStrings` does not contain what we want is when an existing roll call is looked at / re-opened. But in this case, it should be empty and if we scan more tokens it will be a superset?

i.e. something like

```typescript
const attendeePopTokens = useMemo(() =>
    (attendeePopTokensStrings ?
        attendeePopTokensStrings.map((k) => new PublicKey(k) : 
        rollCall?.attendees
    ) || []
 , [attendeePopTokensStrings, rollCall?.attendees]);
```

Or am I missing something?

2023-04-20 09:47 UTC, MeKHell submitted a review, later dismissed
LGTM !

2023-04-23 18:57 UTC, Tyratox commented on fe1-web/src/features/rollCall/screens/__tests__/ViewSingleRollCall.test.tsx
> +    });
Not sure if these tests still accomplish what the comment describes?

2023-04-23 18:58 UTC, Tyratox commented
Otherwise LGTM :)

2023-04-26 09:49 UTC, Tyratox approved these changes

2023-04-26 09:50 UTC, Tyratox commented
Sorry I was dumb, it makes after the discussion in the meeting :)

2023-05-01 07:42 UTC, merged