Work be2 amine add support for responses with map
dedis/popstellar pull request #1513
Opened 2023-04-22 10:11 UTC by BelghmiAmine

This little pull request adds a map parameter to the ResultObject Type so that the server can send the map of missing ids when receiving a heartbeat as a response.

2023-04-22 10:20 UTC, K1li4nL approved these changes

2023-04-23 10:45 UTC, Ajkunas approved these changes

2023-04-23 10:47 UTC, Ajkunas requested changes
Just a tiny comment, otherwise all good. 
I am a bit confused: the changes are also done in your previous PR ParamsMapHandler right ?

2023-04-23 10:47 UTC, Ajkunas commented on be2-scala/src/main/scala/ch/epfl/pop/model/network/ResultObject.scala
> +        this.resultInt == that.resultInt && that.resultMessages == this.resultMessages && that.resultMap == this.resultMap
```suggestion
        this.resultInt == that.resultInt && 
        that.resultMessages == this.resultMessages && 
        that.resultMap == this.resultMap
```

2023-04-23 10:47 UTC, Ajkunas commented on be2-scala/src/main/scala/ch/epfl/pop/model/network/ResultObject.scala
> +        this.resultInt == that.resultInt && that.resultMessages == this.resultMessages && that.resultMap == this.resultMap
More clear to split up the lines

2023-04-24 20:29 UTC, K1li4nL commented
Not needed anymore

2023-04-24 20:29 UTC, closed without merging