Add persistency layers to the application
dedis/popstellar pull request #1528
Opened 2023-04-28 22:42 UTC by matteosz

This PR resolves #1383 . 

- Each repository is assigned a persistency layer, based on Room SQL databases. Additionally, some of the repositories that require frequent access use a LRU cache to speed up.

- The core data (server address, subscriptions and wallet seed) is also migrated to this new storage system, this resolves #1407 .

- Currently the query operations on the database are done on the main thread, which is not a good practice and they should be migrated to other threads

2023-05-04 20:39 UTC, simone-kalbermatter requested changes
A lot of impressive work 😄 Just some comments.

2023-05-04 20:39 UTC, simone-kalbermatter commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/repository/MessageRepository.java
> +  /** This function is called on creation to asynchronously full the cache */
Just a typo

2023-05-04 20:39 UTC, simone-kalbermatter commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/repository/MessageRepository.java
> +          .doOnComplete(() -> Timber.tag(TAG).d("Persisted message %s", messageID))
It would be good to also add a `doOnError` that logs errors here.

2023-05-04 20:39 UTC, simone-kalbermatter commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/repository/LAORepository.java
> +        .observeOn(AndroidSchedulers.mainThread())
Would be good to add a `doOnError()` here and log the error

2023-05-05 07:16 UTC, simone-kalbermatter submitted a review, later dismissed
LGTM!

2023-05-10 05:53 UTC, Warhedgehog requested changes
Impressive Work, very clean ! A couple things 🙂

2023-05-10 05:53 UTC, Warhedgehog commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/repository/MessageRepository.java
> +          .subscribe();
Same here

2023-05-10 05:53 UTC, Warhedgehog commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/repository/database/core/CoreEntity.java
> +  }
Could you copy the arrays ? Also no need to add the suffix copy for the one where you did

2023-05-10 05:53 UTC, Warhedgehog commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/repository/database/lao/LAOEntity.java
> +    return lao;
As the `Lao` class is not immutable, could you return copy ?

2023-05-10 05:53 UTC, Warhedgehog commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/ui/home/HomeViewModel.java
> +  public boolean restoreConnections(Context context) {
There is no need to add the context in argument. You can use `getApplication().getApplicationContext()`

2023-05-10 10:19 UTC, matteosz commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/repository/LAORepository.java
> +        .subscribe();
Yeah I'll transfer the onComplete/on Error in the subscribe and then I'll add it to a disposable attached to the applications lifecycle to dispose the resources on the application's destroy

2023-05-10 16:12 UTC, Warhedgehog requested changes
Looks good. Just the one comment

2023-05-10 16:12 UTC, Warhedgehog commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/utility/NetworkLogger.java
> -        });
I'd add a comment explaining there's nothing to be done if not in Energy Saving mode

2023-05-12 20:28 UTC, Warhedgehog approved these changes

2023-05-12 20:28 UTC, Warhedgehog approved these changes

2023-05-14 15:11 UTC, Warhedgehog approved these changes

2023-05-14 15:57 UTC, merged