add frontend class
dedis/popstellar pull request #1550
Opened 2023-05-05 14:02 UTC by simone-kalbermatter

2023-05-25 13:19 UTC, matteosz submitted a review, later dismissed
LGTM!

2023-05-28 21:26 UTC, GabrielFleischer requested changes
I am truly amazed by the work you've done !

This is so much better and on top of that, the code is clear and documented.

I was only able to find a formatting mistake 😅

I also have a question regarding a modification you did when starting the Go Server.

2023-05-28 21:26 UTC, GabrielFleischer commented on tests/karate/src/test/java/common/net/MultiMsgWebSocketClient.java
> +
Slight formatting mistake 😉

2023-05-28 21:26 UTC, GabrielFleischer commented on tests/karate/src/test/java/be/utils/GoServer.java
> +        "./pop server serve"
I have a question :
How is the organizer key given to the server without this argument ?

2023-06-01 06:39 UTC, GabrielFleischer commented on tests/karate/src/test/java/be/utils/GoServer.java
> +        "./pop server serve"
Oh ok, that's something I didn't follow. Thanks for the clarification.

2023-06-01 06:40 UTC, GabrielFleischer approved these changes
LGTM

2023-06-03 22:21 UTC, merged