Display witness messages
dedis/popstellar pull request #1557
Opened 2023-05-08 11:48 UTC by simone-kalbermatter

This PR changes the Messages tab in the witnessing menu to diplay the messages that require witnessing. Most of the logic was already there, it was just not displayed correctly. The message types that require witnessing so far implemented were:
- SetupElection
- CreateRollCall
- OpenRollCall
- Close Roll Call
- UpdateLao
- CreateMeeting
- State Meeting

For attendees, the messages are displayed but the sign button is not shown.
On click of the sign button, a dialog pops up to ask if the user really wants to sign the message. On confirmation, a witness message is sent, but this is not fully implemented yet and a handler will be added later.

###   Witness and organizer UI
<img src="https://user-images.githubusercontent.com/71314469/236949152-17014e1a-07e6-4921-ada6-59baa918972b.png" 
     width="250" />

expanded:

<img src="https://user-images.githubusercontent.com/71314469/236949885-232f3893-d4cd-4e5a-bc57-05d377cf7dc7.png" 
     width="250" />

On click of the sign button:

<img src="https://user-images.githubusercontent.com/71314469/236950157-262863a8-46ce-4945-855e-51a79569f4aa.png" 
     width="250" />

###   Attendee UI
sign button not displayed:

<img src="https://user-images.githubusercontent.com/71314469/236949272-f761487d-5874-4872-b4ef-5cb523811167.png" 
     width="250" />

###   Attendee UI in light mode

<img src="https://github.com/dedis/popstellar/assets/71314469/b60a2971-ba6a-4534-b1c8-5c9500a36085.png" 
     width="250" />

<img src="https://github.com/dedis/popstellar/assets/71314469/0ee43370-e767-4387-8c68-cdb083d2a685.png" 
     width="250" />

2023-05-09 21:10 UTC, matteosz requested changes
Good job! Just some very picky comments 😄

2023-05-09 21:10 UTC, matteosz commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/ui/lao/witness/WitnessMessageListViewAdapter.java
> +      return witnesses.stream().map(Base64URLData::getEncoded).collect(Collectors.joining("\n"));
Same here regarding `PublicKey::getEncoded`

2023-05-09 21:10 UTC, matteosz commented on fe2-android/app/src/test/ui/robolectric/com/github/dedis/popstellar/ui/lao/witness/WitnessingFragmentTest.java
> +
Can you transfer that to the utils class for the matcher (MatcherUtils) or to the PageObject, so it's more reusable also in the future?

2023-05-09 22:36 UTC, matteosz approved these changes
LGTM!

2023-05-10 16:27 UTC, Warhedgehog reviewed
I'll review your PR later this week, in the meantime, could you fix code smell #1? Also a screenshot of the result in day theme would be cool 🙂

2023-05-12 20:59 UTC, Warhedgehog approved these changes
Impressive work ! Well documented and tested

2023-05-12 20:59 UTC, Warhedgehog approved these changes
Impressive work ! Well documented and tested

2023-05-12 21:50 UTC, merged