Work be2 amine bug fix karate testing
dedis/popstellar pull request #1610
Opened 2023-05-26 13:37 UTC by BelghmiAmine

This pull request fixes a couple of bugs detected by the karate tests :

2023-06-01 12:50 UTC, Ajkunas requested changes
Reviewed a bit the PR :) I just have some comments concerning some implementations to make it more concise, othw all good

2023-06-06 22:03 UTC, Ajkunas requested changes
Last nitpicks and it's ready to be approved !

2023-06-06 22:03 UTC, Ajkunas commented on be2-scala/src/main/scala/ch/epfl/pop/pubsub/graph/validators/ElectionValidator.scala
> +        if (setupElectionTimeStamp.isEmpty) {
Same comment as below. 
I would suggest you to use a match case instead.

2023-06-16 06:57 UTC, pierluca approved these changes
Approving blindly :)

2023-06-17 09:12 UTC, Ajkunas approved these changes

2023-06-19 07:34 UTC, merged