Fix CI tests and general concurrency issues
dedis/popstellar pull request #1611
Opened 2023-05-27 16:34 UTC by matteosz

This PR resolves #1608.
- It replaces synchronization of methods for a more elegant and efficient usage on concurrent thread-safe data structures.
- It improves the documentation of the repositories
- It suppresses some warning logs during tests generated by the missing closure of the db connection which were slowing down the execution

2023-05-27 21:41 UTC, simone-kalbermatter submitted a review, later dismissed
LGTM, well documented!

2023-05-29 20:37 UTC, Warhedgehog requested changes
Just the small detail in the comment. Great work !

2023-05-29 20:37 UTC, Warhedgehog commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/repository/RollCallRepository.java
> +   * This function retrieves a roll call from the repository given its ephemeral identifier.
I'd prefer state-dependant identifier

2023-05-30 14:33 UTC, Warhedgehog approved these changes
LGTM

2023-05-30 14:38 UTC, merged