Witnessing policy #2
dedis/popstellar pull request #1631
Opened 2023-06-02 13:05 UTC by matteosz

This PR addresses the open issue left by the previous PR (#1582).

It simply provides a way of storing and making persistent pending objects (i.e. objects which have been received as message but not yet reached the threshold of witness signatures). So, now the user can exit the application and the pending objects will be restored.

2023-06-04 23:39 UTC, simone-kalbermatter approved these changes
LGTM!

2023-06-05 16:22 UTC, Warhedgehog requested changes
Great work ! I've not reviewed the test yet but for the rest I just have the sole request :)

2023-06-05 16:22 UTC, Warhedgehog commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/repository/WitnessingRepository.java
Could you add some documentation to the class please ? Mainly the general witnessing policy and how persistence impacts it. I think this would be rather complex to understand for a newcomer

2023-06-05 16:23 UTC, Warhedgehog commented
Also, I think that it is now quite necessary to update the android documentation, in a separate PR, for the witnessing and the persistence parts

2023-06-05 17:24 UTC, matteosz commented
> Also, I think that it is now quite necessary to update the android documentation, in a separate PR, for the witnessing and the persistence parts

Yeah, I was planning to update it now that the work is essentially finished

2023-06-06 05:25 UTC, Warhedgehog approved these changes
LGTM !

2023-06-06 08:25 UTC, merged