Update FE2 documentation
dedis/popstellar pull request #1646
Opened 2023-06-06 08:43 UTC by matteosz

2023-06-06 14:38 UTC, simone-kalbermatter approved these changes
LGTM!

2023-06-07 13:31 UTC, Warhedgehog requested changes
Great work. Just the typo

2023-06-07 13:31 UTC, Warhedgehog commented on fe2-android/docs/README.md
> +There's no a default behaviour of storing and retrieving the persistent state of a repository, so here's more details:
Typo :)

2023-06-07 13:32 UTC, Warhedgehog commented on fe2-android/docs/README.md
> +There's no a default behaviour of storing and retrieving the persistent state of a repository, so here's more details:
Sorry it's at the start of line 289

2023-06-07 19:24 UTC, Warhedgehog approved these changes
LGTM

2023-06-07 22:24 UTC, merged