Work be2 thibault enum refactor
dedis/popstellar pull request #1763
Opened 2024-02-28 10:21 UTC by t1b00

Refactored enums into parametrized enums

2024-02-28 10:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dedis/popstellar?pullRequest=1763) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dedis/popstellar?pullRequest=1763) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dedis/popstellar?pullRequest=1763) it.</sub>

2024-03-20 00:43 UTC, onsriahi14 approved these changes

2024-03-20 09:07 UTC, K1li4nL requested changes
Nice work and nice coverage ! Just a few things I believe should be changed (can be discussed though)

2024-03-20 09:07 UTC, K1li4nL commented on be2-scala/src/test/scala/ch/epfl/pop/json/MessageDataProtocolSuite.scala
> +  }
I think it would be nice to separate the two (valid and invalid) case so its easier to see what failed

2024-03-20 09:07 UTC, K1li4nL commented on be2-scala/src/test/scala/ch/epfl/pop/json/MessageDataProtocolSuite.scala
> +    }
I think it would be nice to separate the two (valid and invalid) case so its easier to see what failed

2024-03-20 09:07 UTC, K1li4nL commented on be2-scala/src/test/scala/ch/epfl/pop/json/MessageDataProtocolSuite.scala
> +  }
I think it would be nice to separate the two (valid and invalid) case so its easier to see what failed

2024-03-24 17:44 UTC, t1b00 commented on be2-scala/src/test/scala/ch/epfl/pop/json/HighLevelProtocolSuite.scala
> +  }
You're completely right, changed it now :)

2024-03-24 17:44 UTC, t1b00 commented on be2-scala/src/test/scala/ch/epfl/pop/json/MessageDataProtocolSuite.scala
> +    val messageData = CastVoteElection.buildFromJson(example) // here
I was trying to find where the json was used and forgot to remove the comment

2024-03-24 19:34 UTC, K1li4nL requested changes
A nitpick and a last test that need to be broken in two, after that all should be good for me !

2024-03-24 19:34 UTC, K1li4nL commented on be2-scala/src/test/scala/ch/epfl/pop/json/HighLevelProtocolSuite.scala
> +  }
I think you forgot to break that test in two tests :grin:

2024-03-24 20:52 UTC, K1li4nL approved these changes
LGTM !

2024-03-24 21:05 UTC, merged