Trying to fix CI node_modules caching issue #847
dedis/popstellar pull request #1771
Opened 2024-03-04 14:16 UTC by osm-alt

Added the node_modules path to the caching action of the workflow for fe1-web.

2024-03-04 14:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dedis/popstellar?pullRequest=1771) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dedis/popstellar?pullRequest=1771) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dedis/popstellar?pullRequest=1771) it.</sub>

2024-03-05 10:15 UTC, osm-alt commented
Removed caching of node_modules on MacOS due to my previous comment but left it for the other platforms

2024-03-06 13:13 UTC, 4xiom5 submitted a review, later dismissed
Seems good

2024-03-11 09:21 UTC, Tyratox requested changes
Maybe add a small comment/explanation why macOS is excluded, otherwise LGTM!

2024-03-11 09:21 UTC, Tyratox commented on .github/workflows/ci.yaml
> +        if: ${{ runner.os != 'macOS'}}
Why exclude MacOs? Maybe add a comment?

2024-03-11 09:37 UTC, Tyratox approved these changes

2024-03-11 09:47 UTC, merged