jsonRPC handle of rumor msg in scala backend
dedis/popstellar pull request #1799
Opened 2024-04-06 17:10 UTC by DanielTavaresA

Based on PR #1789 , handles and tests the new rumor jsonRPC message.

Can read an incoming rumor jsonRPC, convert it to a Rumor object containing its respective objects : - serverId : PublicKey, rumorId : Int, messages : [Channel, Array[Messages]]. Can also do the reverse operation and write to a jsonRPC Rumor

2024-04-14 09:30 UTC, t1b00 commented on be2-scala/src/main/scala/ch/epfl/pop/json/HighLevelProtocol.scala
> +          val map = mutable.HashMap[Channel, Array[Message]]()
I think you can reduce the complexity of this, especially the use of a mutable HashMap
Try:
val map: Map[Channel, Array[Message]] = rumors.asJsObject.fields.map {
  case (k: String, JsArray(v)) => Channel(k) -> v.map(_.convertTo[Message]).toArray
  case _                       => throw new IllegalArgumentException(s"Unrecognizable rumor in $json")
}

Tested it and it passes the tests

2024-04-14 09:31 UTC, t1b00 requested changes
Just one detail on the use of a mutable HashMap which could be simplified (see comment), otherwise LGTM

2024-04-14 14:37 UTC, onsriahi14 commented on be2-scala/src/main/scala/ch/epfl/pop/json/HighLevelProtocol.scala
> +      jsonObject.getFields(PARAM_SENDER_PK, PARAM_RUMOR_ID, PARAM_MESSAGES) match {
maybe here you can do json.asJsObject.getFields directly without the need to create the variable jsonObject

2024-04-14 19:27 UTC, K1li4nL requested changes
Coverage and a few comments / question before we can move on ;)

2024-04-14 19:27 UTC, K1li4nL commented on be2-scala/src/main/scala/ch/epfl/pop/model/network/method/Rumor.scala
> +final case class Rumor(senderPk: PublicKey, rumorId: Int, messages: Map[Channel, Array[Message]]) extends Params {
Is there a good reason to use a mutable array instead of an immutable list here ?  I believe we should stick to Scala preferred type to be able to better exploit `yield`, `foreach` or `match` in the rest of the code

2024-04-14 19:27 UTC, K1li4nL commented on be2-scala/src/test/scala/util/examples/json/rumor/exampleRumor.scala
There is a `readJsonFromFile` function in `IOHelper.scala` that could prevent this copy of json ;)

2024-04-14 19:27 UTC, K1li4nL commented on be2-scala/src/test/scala/util/examples/json/rumor/exampleRumor.scala
It would then allow you to test easily the wrong examples as well

2024-04-17 09:54 UTC, K1li4nL approved these changes
Good job, looks good to me !

2024-04-18 08:21 UTC, t1b00 approved these changes

2024-04-18 08:26 UTC, K1li4nL approved these changes

2024-04-18 09:49 UTC, merged