Reduce heartbeatbuild logic duplication
dedis/popstellar pull request #1808
Opened 2024-04-14 13:00 UTC by onsriahi14

2024-04-14 14:52 UTC, t1b00 reviewed
There's a few minor code quality tweaks that are possible but other than that LGTM!

2024-04-14 14:52 UTC, t1b00 commented on be2-scala/src/main/scala/ch/epfl/pop/Server.scala
> +      // val heartbeatGenRef: ActorRef = system.actorOf(HeartbeatGenerator.props(dbActorRef))
Could be good to remove the unnecessary code :)

2024-04-14 14:52 UTC, t1b00 commented on be2-scala/src/main/scala/ch/epfl/pop/decentralized/Monitor.scala
> +          case Failure(ex: DbActorNAckException)                       => HashMap.empty[Channel, Set[Hash]] // Specific failure
Why keep the specific failure if the handling is the same as the case _? Isn't it possible to combine both?

2024-04-14 14:52 UTC, t1b00 commented on be2-scala/src/main/scala/ch/epfl/pop/storage/DbActor.scala
> +    setOfChannels.foreach(channel => {
I think you can replace this by a setOfChannels.map and avoid the HashMap creation

2024-04-14 20:12 UTC, K1li4nL requested changes
Lots of moving parts in the code you are touching, good job overall ! Some nitpicks and some simplification that I believe could make the code better

2024-04-14 20:12 UTC, K1li4nL commented on be2-scala/src/test/scala/ch/epfl/pop/decentralized/MonitorSuite.scala
The following test are causing some `Future timed out after [1 second]` logs which are not very reassuring: 

- [ ] "monitor should not schedule any heartbeats when receiving a heartbeat or get_messages_by_id"
- [ ] "monitor should send heartbeats if and only if servers are connected"
- [ ] "monitor should send ConnectTo() requests to ConnectionMediator upon relevant config file change besides first read"

2024-04-15 07:56 UTC, t1b00 approved these changes

2024-04-18 15:26 UTC, onsriahi14 commented on be2-scala/src/main/scala/ch/epfl/pop/pubsub/graph/handlers/ParamsWithMapHandler.scala
> +          }
map is immutable and localHeartbeat is mutable so i cannot assign map directly to localHeartbeat that's why i copied it

2024-04-19 08:06 UTC, K1li4nL commented on be2-scala/src/main/scala/ch/epfl/pop/pubsub/graph/handlers/ParamsWithMapHandler.scala
> +          }
From what I see in the rest of the code, we don't need it to be mutable ?

2024-04-19 14:48 UTC, K1li4nL requested changes
Last comments, after that we should be good !

2024-04-19 14:48 UTC, K1li4nL commented on be2-scala/src/main/scala/ch/epfl/pop/storage/DbActor.scala
> +  private def generateHeartbeat(): Option[HashMap[Channel, Set[Hash]]] = {
I feel like an `Option` is not necessary here, you might as well return an empty map directly ?

2024-04-19 14:48 UTC, K1li4nL commented on be2-scala/src/test/scala/ch/epfl/pop/decentralized/MonitorSuite.scala
> +
blank line

2024-04-19 14:48 UTC, K1li4nL commented on be2-scala/src/test/scala/ch/epfl/pop/decentralized/MonitorSuite.scala
> +
blank line

2024-04-19 14:48 UTC, K1li4nL commented on be2-scala/src/test/scala/ch/epfl/pop/storage/DbActorSuite.scala
> +
blank line

2024-04-19 20:20 UTC, K1li4nL approved these changes
LGTM !

2024-04-19 21:46 UTC, merged