change signature of readRumor for more intuitive
dedis/popstellar pull request #1844
Opened 2024-05-02 14:38 UTC by DanielTavaresA

Changed from readRumors (db handle multiples queries at once) to readRumor that handles only one query at time. This shifts the responsibility of handling multiples query to the querier. It makes the use of the database more intuitive

2024-05-03 08:53 UTC, t1b00 submitted a review, later dismissed

2024-05-04 16:56 UTC, K1li4nL requested changes
Just a typo otherwise LGTM

2024-05-04 16:56 UTC, K1li4nL commented on be2-scala/src/main/scala/ch/epfl/pop/storage/DbActor.scala
> +  final case class DbActorReadRumors(foundRumor: Option[Rumor]) extends DbActorMessage
If it returns only one rumor:
```suggestion
  final case class DbActorReadRumor(foundRumor: Option[Rumor]) extends DbActorMessage
```

2024-05-04 16:56 UTC, K1li4nL commented on be2-scala/src/main/scala/ch/epfl/pop/storage/DbActor.scala
> +  final case class ReadRumors(desiredRumor: (PublicKey, Int)) extends Event
If it returns only one rumor:
```suggestion
  final case class ReadRumor(desiredRumor: (PublicKey, Int)) extends Event
```

2024-05-06 07:20 UTC, K1li4nL approved these changes
LGTM !

2024-05-06 08:19 UTC, merged