Store election result messages
dedis/popstellar pull request #848
Opened 2022-02-25 17:35 UTC by Tyratox

When working on https://github.com/dedis/popstellar/issues/703 I noticed that election result messages are not sent to a new client connecting after sending a catchup message. The reason is that the election#result messages are not stored when broadcasting them. This pull request fixes this.

Compare
https://github.com/dedis/popstellar/blob/ab162f1cb2122f10dafbac003979abbfee4ac862/be1-go/channel/election/mod.go#L343-L344

and

https://github.com/dedis/popstellar/blob/ab162f1cb2122f10dafbac003979abbfee4ac862/be1-go/channel/election/mod.go#L384-L385

to

https://github.com/dedis/popstellar/blob/ab162f1cb2122f10dafbac003979abbfee4ac862/be1-go/channel/election/mod.go#L430-L435.

2022-02-25 20:52 UTC, Warhedgehog requested changes
Per the slack message, without further clarifications, I do not think it is a desirable change since the documentation says that the inbox storage is for incoming message

2022-02-28 12:06 UTC, Tyratox commented
> Noémien: IIRC we decided to store everything in the inbox, and filter out unnecessary messages when sending a catchup. In this case implementing a persistence layer would only require to persist the inbox, and replay the inbox content to recover the state of an organiser.

It seems then that this comment should be updated as well? Should I include that in this PR or will you do this on a different branch & PR?

2022-03-02 15:22 UTC, Tyratox commented
Good points! I do not have a full overview over the project but it seems like a good solution as other servers, for example the witnesses, probably should get the results as well. I will ask in the evoting channel for confirmation and update this reply as soon as I get an answer.

In any case it should just be made sure that this also happens if there is no other server.

2022-03-03 10:44 UTC, Tyratox commented
> [Louis-Henri](https://app.slack.com/team/UMRHRP1K5)  [vor 18 Stunden](https://dedis.slack.com/archives/C03442XUBCK/p1646239534435329?thread_ts=1646234776.541329&cid=C03442XUBCK)
> Election Result I believe should be signed by the witnesses to say that we witness and agree to the Election result (bearbeitet) 
> 
> Before it is sent to the clients. Otherwise clients are unsure whether to accept the result or not.
> 
> This would require witness signing between the organizers and witnesses which relies on server-2-server communication.

2022-03-07 14:49 UTC, closed without merging