Create the JSON schema of a Digital Cash transaction
dedis/popstellar pull request #869
Opened 2022-03-08 16:00 UTC by 0xdieman

Schema of a Digital Cash transaction posting.
Each object representation in an array is given by the field "items".

2022-03-13 10:54 UTC, lourkeur requested changes
I think we should link into the parent schema:  48c981a08deac4f1212716fcaa48bdc3d0cf5d18

I have played with an example transaction, the schema is too permissive because there are things about it that should not validate: 3d592923d4457f3a9c1bdd633a40c536279e3884

2022-03-13 10:54 UTC, lourkeur commented on protocol/query/method/message/data/dataCashTransaction.json
> +          "properties": {
This node should specify `required` properties. Right now `[{}]` is a valid TxIn

2022-03-13 10:54 UTC, lourkeur commented on protocol/query/method/message/data/dataCashTransaction.json
> +          "properties": {
Same here

2022-03-13 10:54 UTC, lourkeur commented on protocol/query/method/message/data/dataCashTransaction.json
> +    "transaction": {
`"transaction": {}` should not be valid. I think this should contain `{ "object": { "properties": ... }}` instead of `"Version"` directly.

2022-03-13 14:35 UTC, zoemarin commented
And perhaps also change the label Script like 35 and 75,And give some other name like Lock and Unllock ? Zoé MarinVon: Louis Bettens ***@***.***>Gesendet: Sonntag, 13. März 2022, 11:54An: dedis/popstellar ***@***.***>Cc: zoemarin ***@***.***>; Review requested ***@***.***>Betreff: Re: [dedis/popstellar] Create the JSON schema of a Digital Cash transaction  (PR #869)
@lourkeur requested changes on this pull request.

I think we should link into the parent schema:  48c981a
I have played with an example transaction, the schema is too permissive because there are things about it that should not validate: 3d59292

In protocol/query/method/message/data/dataCashTransaction.json:
> +    },
+    "action": {
+      "const": "post"
+    },
+    "transaction": {
+      "Version": {
+        "type": "integer",
+        "description": "The version of the transaction inputs"
+      },
+      "TxIn": {
+        "type": "array",
+        "description": "[Array[Objects]] array of output transactions to use as inputs",
+        "items": {
+          "type": "object",
+          "description": "Object representing a transaction output to use as an input for this transaction",
+          "properties": {

This node should specify required properties. Right now [{}] is a valid TxIn



In protocol/query/method/message/data/dataCashTransaction.json:
> +            },
+            "Sequence": {
+              "type": "bytes",
+              "length": "4",
+              "$comment": "Set as 0xFFFFFFFF"
+            }
+          }
+        }
+      },
+      "TxOut": {
+        "type": "array",
+        "description": "[Array[Objects]] array of outputs from this transactions",
+        "items": {
+          "type": "object",
+          "description": "Object representing an output of this transaction",
+          "properties": {

Same here



In protocol/query/method/message/data/dataCashTransaction.json:
> @@ -0,0 +1,100 @@
+{
+  "$schema": "http://json-schema.org/draft-07/schema#",
+  "$id": "https://raw.githubusercontent.com/dedis/popstellar/master/protocol/query/method/message/data/dataPostTransaction.json",
+  "title": "Post a digital cash transaction",
+  "type": "object",
+  "properties": {
+    "object": {
+      "const": "transaction"
+    },
+    "action": {
+      "const": "post"
+    },
+    "transaction": {

"transaction": {} should not be valid. I think this should contain { "object": { "properties": ... }} instead of "Version" directly.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because your review was requested.Message ID: ***@***.***>

2022-03-18 21:54 UTC, lourkeur requested changes

2022-03-18 21:54 UTC, lourkeur commented on protocol/query/method/message/data/dataCashTransaction.json
> +                "length": "4",
```suggestion
                "type": "integer",
```

I think `bytes` isn't a type:
`$.transaction.TxIn[0].Sequence: object found, unknown expected`

2022-03-18 21:54 UTC, lourkeur commented on protocol/query/method/message/data/dataCashTransaction.json
> +              "Script": {
The `{}` script is allowed. there should be required fields.

2022-03-22 12:06 UTC, lourkeur approved these changes
LGTM.

As far as what Zoé said about script naming conventions I am ambivalent.

2022-03-24 14:24 UTC, lourkeur requested changes
Honestly let's just remove this field if it's just going to be a meaningless constant

Pros:
- it looks like bitcoin.

Cons:
- it holds 0 useful information.
- It's more work to implement and maintain for no benefit.
- code is read more often than it is written. If you have code that serves no purpose it's very confusing, so you should remove it.
- We can add it later. Unlike bitcoin transactions this isn't a byte-offset format so we don't need to plan ahead.
- "Simplicity 👈" —Pierluca, 2022

2022-03-24 14:24 UTC, lourkeur commented on protocol/query/method/message/data/dataCashTransaction.json
> +                "contentEncoding": "base64",
why base64

2022-03-26 08:10 UTC, haoqianzhang submitted a review, later dismissed
Looks good to me.

2022-03-26 08:12 UTC, haoqianzhang commented on protocol/query/method/message/data/dataCashTransaction.json
> +                "contentEncoding": "base64",
Feel free to omit the sequence.

2022-03-27 19:36 UTC, MaximeZmt approved these changes
👍

2022-03-28 11:50 UTC, lourkeur approved these changes

2022-03-30 12:10 UTC, haoqianzhang approved these changes
Looks good.

2022-03-30 13:49 UTC, MaximeZmt requested changes
I think we should update that file too in order to reference it in the protocol  https://github.com/dedis/popstellar/blob/master/protocol/query/method/message/data/data.json 😅

2022-03-30 13:54 UTC, MaximeZmt approved these changes

2022-03-30 14:16 UTC, haoqianzhang approved these changes

2022-03-31 07:16 UTC, merged