fe2 android Some first communication
dedis/popstellar pull request #904
Opened 2022-03-29 13:50 UTC by zoemarin

I start to create a dummie transaction

2022-03-29 13:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dedis/popstellar?pullRequest=904) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dedis/popstellar?pullRequest=904) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dedis/popstellar?pullRequest=904) it.</sub>

2022-04-01 12:35 UTC, jbsv commented
It's hard to see what part of this PR is about communication. This PR is very similar to the 903. Maybe you could branch off the previous branch (see PR 903), and create a PR that will merge into this previous branch. This way you would have only the diff between the 2 branches.

2022-04-01 18:26 UTC, ahominal reviewed
Great work !

2022-04-01 18:26 UTC, ahominal commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/ui/digitalcash/DigitalCashMain.java
> +        // When we launch the social media from a lao, it directly sets its id and name
Maybe create a variable for getIntent().getExtras()?

2022-04-01 18:26 UTC, ahominal commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/ui/digitalcash/DigitalCashViewModel.java
> +   * Getters for MutableLiveData instances declared above
Maybe add comment for events? at least which fragment is calling them? It becomes a mess to read and understand when they accumulate :)

2022-04-01 18:26 UTC, ahominal commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/ui/digitalcash/DigitalCashViewModel.java
> +   * Getters for MutableLiveData instances declared above
Maybe add comment for events? at least which fragment is calling them? It becomes a mess to read and understand when they accumulate :)

2022-04-05 07:47 UTC, Tesa27 requested changes
Lot of commented code is present

2022-04-05 07:47 UTC, Tesa27 commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/model/objects/Address.java
> +    //String receiver_address;
We should not have commented code

2022-04-05 07:47 UTC, Tesa27 commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/model/objects/Lao.java
> +  // Map <Public Key, Transaction>
Same as above

2022-04-05 07:47 UTC, Tesa27 commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/ui/detail/LaoDetailActivity.java
> +    //setupSocialMediaButton();
same as above

2022-04-05 07:47 UTC, Tesa27 commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/ui/detail/LaoDetailActivity.java
> +    // setupSocialMediaActivity();
same as above

2022-04-05 07:47 UTC, Tesa27 commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/ui/digitalcash/DigitalCashSendFragment.java
> +    // } else {
same as above

2022-04-05 07:47 UTC, Tesa27 commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/ui/digitalcash/DigitalCashViewModel.java
> +    //AddDummyTransaction addTransaction = new AddDummyTransaction(amount,sender_address,receiver_address);
same as above

2022-04-05 07:47 UTC, Tesa27 commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/ui/home/HomeActivity.java
> +    // setupSocialMediaButton();
same as above

2022-04-05 07:47 UTC, Tesa27 commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/ui/home/HomeActivity.java
> +  //}
same as above

2022-04-05 07:47 UTC, Tesa27 commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/ui/home/HomeActivity.java
> +  // }
same as above

2022-04-05 07:47 UTC, Tesa27 commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/ui/home/HomeViewModel.java
> +      //new MutableLiveData<>();
same as above

2022-04-05 07:47 UTC, Tesa27 commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/ui/home/HomeViewModel.java
> +  //}
same as above

2022-04-05 07:47 UTC, Tesa27 commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/ui/home/HomeViewModel.java
> +  //}
same as above

2022-05-04 13:21 UTC, closed without merging