Add basic implementation of greeting method to FE2
dedis/popstellar pull request #952
Opened 2022-04-13 12:46 UTC by ahominal

This pull request follows Nico's suggestion of implementation of the new the protocol for encrypted e-voting described here https://github.com/dedis/popstellar/pull/917 .

This pull request contains:
- basic "Greeting" message implementation
- basic "Server / Peer object" saving backend's info on frontend
- handling of the Greeting
- added global Server Repository (Map<LaoId, Server>)

2022-04-27 13:39 UTC, GabrielFleischer requested changes
Please merge master into the branch 😉

2022-05-02 14:46 UTC, Tesa27 requested changes
Looks good overall, I did not go into detail on this PR but seems to be coherent with fe1, just a minor detail.

2022-05-02 14:46 UTC, Tesa27 commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/repository/ServerRepository.java
> +    } else {
You can drop the else here

2022-05-02 15:02 UTC, GabrielFleischer commented on fe2-android/app/src/test/java/com/github/dedis/popstellar/utility/handler/ChirpHandlerTest.java
> +@HiltAndroidTest
You do not need to use Hilt there. You can just create the serverRepository through its constructor.
`new ServerRepository()`

2022-05-02 15:03 UTC, GabrielFleischer commented on fe2-android/app/src/test/java/com/github/dedis/popstellar/utility/handler/ConsensusHandlerTest.java
> +@HiltAndroidTest
Same here

2022-05-02 15:03 UTC, GabrielFleischer commented on fe2-android/app/src/test/java/com/github/dedis/popstellar/utility/handler/RollCallHandlerTest.java
> +@HiltAndroidTest
And here 😄

2022-05-02 15:27 UTC, ahominal commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/model/network/method/message/data/lao/GreetLao.java
> +  private String frontendKey;
Ohh that's why i didn't use it, thanks !

2022-05-02 15:28 UTC, ahominal commented on fe2-android/app/src/main/java/com/github/dedis/popstellar/repository/ServerRepository.java
> +    } else {
thanks for noticing !

2022-05-04 13:54 UTC, GabrielFleischer approved these changes
LGTM

2022-05-08 07:07 UTC, zoemarin approved these changes
Seems Fine to me :)

2022-05-08 07:34 UTC, Tesa27 approved these changes
LGTM but for some reason tests for fe1 keep failing

2022-05-08 15:40 UTC, Tyratox commented
Yes the tests for fe-1 fail because the protocol specification (json schema) was changed but this PR does not contain the changes done to fe-1 to support these changes. This is fine since I will merge https://github.com/dedis/popstellar/pull/957 to the same branch as this PR and then both tests should pass :)

2022-05-09 13:03 UTC, merged